In [7]:
import pandas as pd
import numpy as np
import ydata_profiling as yp
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
data = pd.read_csv('../data/data_globant.csv')

display(data.head())

,Date,Email,Name,Position,Seniority,Location,Studio,Client,Client Tag,Project,Project Tag,Team Name,Engagement,Email Leader,Year,Month,Day
0,02Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.04,laura.leon@tec.globant.com,2023,1,2
1,03Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.99,laura.leon@tec.globant.com,2023,1,3
2,04Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.97,laura.leon@tec.globant.com,2023,1,4
3,05Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.75,laura.leon@tec.globant.com,2023,1,5
4,06Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.15,laura.leon@tec.globant.com,2023,1,6

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11366 entries, 0 to 11365
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          11366 non-null  object
 1   Email         11366 non-null  object
 2   Name          11366 non-null  object
 3   Position      11366 non-null  object
 4   Seniority     11366 non-null  object
 5   Location      11366 non-null  object
 6   Studio        11366 non-null  object
 7   Client        11366 non-null  object
 8   Client Tag    11366 non-null  object
 9   Project       11366 non-null  object
 10  Project Tag   11366 non-null  object
 11  Team Name     11366 non-null  object
 12  Engagement    11366 non-null  float64
 13  Email Leader  10226 non-null  object
 14  Year          11366 non-null  int64
 15  Month         11366 non-null  int64
 16  Day           11366 non-null  int64
dtypes: float64(1), int64(3), object(13)
memory usage: 1.5+ MB

In [10]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Engagement,11366.0,2.995252,1.005442,0.0,2.52,3.05,3.6,5.0
Year,11366.0,2023.000000,0.000000,2023.0,2023.00,2023.00,2023.0,2023.0
Month,11366.0,3.540120,1.724827,1.0,2.00,4.00,5.0,6.0
Day,11366.0,15.871547,8.754934,1.0,9.00,16.00,23.0,31.0

In [11]:
data.isna().sum().sort_values(ascending=False)
data.duplicated().sum()

0

In [12]:

profile = yp.ProfileReport(data, title="EDA_preliminar", explorative=True)
profile.to_file("../reports/EDA_preliminar.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 17/17 [00:00<00:00, 67.87it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]