In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('../data/data_globant.csv')

In [4]:
data.head()

,Date,Email,Name,Position,Seniority,Location,Studio,Client,Client Tag,Project,Project Tag,Team Name,Engagement,Email Leader,Year,Month,Day
0,02Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.04,laura.leon@tec.globant.com,2023,1,2
1,03Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.99,laura.leon@tec.globant.com,2023,1,3
2,04Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.97,laura.leon@tec.globant.com,2023,1,4
3,05Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.75,laura.leon@tec.globant.com,2023,1,5
4,06Jan23,natalia.ramirez@tec.globant.com,Natalia Ramírez,Software Developer,Jr,CO/ANT/MED,Engineering,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.15,laura.leon@tec.globant.com,2023,1,6

In [5]:
len(data['Name'].unique())

94

In [6]:
data['Engagement'].notnull().sum()

np.int64(11366)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11366 entries, 0 to 11365
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          11366 non-null  object
 1   Email         11366 non-null  object
 2   Name          11366 non-null  object
 3   Position      11366 non-null  object
 4   Seniority     11366 non-null  object
 5   Location      11366 non-null  object
 6   Studio        11366 non-null  object
 7   Client        11366 non-null  object
 8   Client Tag    11366 non-null  object
 9   Project       11366 non-null  object
 10  Project Tag   11366 non-null  object
 11  Team Name     11366 non-null  object
 12  Engagement    11366 non-null  float64
 13  Email Leader  10226 non-null  object
 14  Year          11366 non-null  int64
 15  Month         11366 non-null  int64
 16  Day           11366 non-null  int64
dtypes: float64(1), int64(3), object(13)
memory usage: 1.5+ MB

In [8]:
data[data['Email Leader'].isnull()]

,Date,Email,Name,Position,Seniority,Location,Studio,Client,Client Tag,Project,Project Tag,Team Name,Engagement,Email Leader,Year,Month,Day
1049,02Jan23,laura.leon@tec.globant.com,Laura León,Project Manager,Sr Level 1,AR/CABA/BA,Delivery,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.40,NaN,2023,1,2
1050,03Jan23,laura.leon@tec.globant.com,Laura León,Project Manager,Sr Level 1,AR/CABA/BA,Delivery,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.45,NaN,2023,1,3
1051,04Jan23,laura.leon@tec.globant.com,Laura León,Project Manager,Sr Level 1,AR/CABA/BA,Delivery,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.96,NaN,2023,1,4
1052,05Jan23,laura.leon@tec.globant.com,Laura León,Project Manager,Sr Level 1,AR/CABA/BA,Delivery,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,3.26,NaN,2023,1,5
1053,06Jan23,laura.leon@tec.globant.com,Laura León,Project Manager,Sr Level 1,AR/CABA/BA,Delivery,GreenWave Innovations,GWI001,Atlas Initiative,ATLINT,Breaking Badger,2.56,NaN,2023,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10988,05Apr23,carlos.ortega@tec.globant.com,Carlos Ortega,Project Manager,Sr Level 2,CO/CUN/BOG,Delivery,EduSmart Systems,EDUSYS,Vanguard Initiative,VGRDIN,The Matrix Mice,3.47,NaN,2023,4,5
10989,06Apr23,carlos.ortega@tec.globant.com,Carlos Ortega,Project Manager,Sr Level 2,CO/CUN/BOG,Delivery,EduSmart Systems,EDUSYS,Vanguard Initiative,VGRDIN,The Matrix Mice,3.14,NaN,2023,4,6
10990,10Apr23,carlos.ortega@tec.globant.com,Carlos Ortega,Project Manager,Sr Level 2,CO/CUN/BOG,Delivery,EduSmart Systems,EDUSYS,Vanguard Initiative,VGRDIN,The Matrix Mice,3.47,NaN,2023,4,10
10991,11Apr23,carlos.ortega@tec.globant.com,Carlos Ortega,Project Manager,Sr Level 2,CO/CUN/BOG,Delivery,EduSmart Systems,EDUSYS,Vanguard Initiative,VGRDIN,The Matrix Mice,3.10,NaN,2023,4,11
10992,12Apr23,carlos.ortega@tec.globant.com,Carlos Ortega,Project Manager,Sr Level 2,CO/CUN/BOG,Delivery,EduSmart Systems,EDUSYS,Vanguard Initiative,VGRDIN,The Matrix Mice,3.67,NaN,2023,4,12

### null email leader

In [9]:
data[data['Email Leader'].isnull()]['Project'].unique()

array(['Atlas Initiative', 'Echo System', 'Horizon Expansion',
       'Nexus Development', 'Odyssey Quest', 'Catalyst Program',
       'Vanguard Initiative', 'Serenity Project'], dtype=object)

In [10]:
data[data['Email Leader'].notnull()]['Project'].unique()

array(['Atlas Initiative', 'Echo System', 'Horizon Expansion',
       'Nexus Development', 'Catalyst Program', 'Odyssey Quest',
       'Serenity Project', 'Vanguard Initiative'], dtype=object)

In [11]:
data[data['Email Leader'].isnull()]['Studio'].unique()

array(['Delivery', 'Engineering', 'Quality Engineering', 'Product'],
      dtype=object)

In [12]:
data[data['Email Leader'].notnull()]['Studio'].unique()

array(['Engineering', 'Product', 'Quality Engineering', 'Cloud Ops',
       'Data', 'Design'], dtype=object)

In [33]:
comb_null = data[data['Email Leader'].isnull()][['Studio', 'Project Tag', 'Position']].drop_duplicates()

In [34]:
comb_null

                    Studio Project Tag                  Position
1049              Delivery      ATLINT           Project Manager
1179           Engineering      ECOSYS       Solutions Architect
1251   Quality Engineering      ECOSYS  Quality Assurance Tester
1299               Product      ECOSYS             Product Owner
2314              Delivery      HOREXP           Project Manager
3070           Engineering      NEXDEV     Technology Consultant
4209              Delivery      ODYQST           Project Manager
4555              Delivery      CATPRO           Project Manager
7590              Delivery      VGRDIN           Project Manager
8344              Delivery      NEXDEV           Project Manager
10813             Delivery      STYPRJ           Project Manager

In [35]:
comb_notnull = data[data['Email Leader'].notnull()][['Studio', 'Project Tag', 'Position']].drop_duplicates()

In [36]:
comb_notnull

                    Studio Project Tag                  Position
0              Engineering      ATLINT        Software Developer
251                Product      ATLINT          Business Analyst
386    Quality Engineering      ATLINT  Quality Assurance Tester
1305               Product      ECOSYS             Product Owner
1431   Quality Engineering      ECOSYS  Quality Assurance Tester
1557           Engineering      ECOSYS        Software Developer
2062   Quality Engineering      HOREXP  Test Automation Engineer
2188           Engineering      HOREXP       Solutions Architect
2440             Cloud Ops      HOREXP           DevOps Engineer
2566             Cloud Ops      HOREXP  Cybersecurity Specialist
3198           Engineering      NEXDEV        Software Developer
3319               Product      NEXDEV          Business Analyst
3445   Quality Engineering      NEXDEV  Test Automation Engineer
3535           Engineering      CATPRO        Software Developer
3536   Quality Engineering      CATPRO  Test Automation Engineer
3890   Quality Engineering      NEXDEV  Quality Assurance Tester
4206   Quality Engineering      ODYQST  Test Automation Engineer
4226   Quality Engineering      CATPRO  Quality Assurance Tester
4406           Engineering      CATPRO     Technology Consultant
4429               Product      CATPRO          Business Analyst
4610               Product      ODYQST          Business Analyst
4985           Engineering      ODYQST        Software Developer
5068                  Data      CATPRO     Business Intelligence
5222             Cloud Ops      CATPRO    Database Administrator
5632                Design      CATPRO  User Experience Designer
5800             Cloud Ops      ODYQST           DevOps Engineer
5979           Engineering      CATPRO       Solutions Architect
6005                  Data      CATPRO              Data Analyst
6502                Design      NEXDEV  User Experience Designer
6628                Design      NEXDEV           Visual Designer
7372                Design      CATPRO           Visual Designer
7435                Design      ODYQST           Visual Designer
7476           Engineering      STYPRJ        Software Developer
7618                  Data      VGRDIN              Data Analyst
7660               Product      VGRDIN          Business Analyst
8477   Quality Engineering      STYPRJ  Test Automation Engineer
8686               Product      STYPRJ          Business Analyst
8880           Engineering      VGRDIN        Software Developer
9734   Quality Engineering      VGRDIN  Test Automation Engineer
10491            Cloud Ops      STYPRJ           DevOps Engineer

In [37]:
df_join = comb_null.merge(comb_notnull, how='inner')

In [38]:
df_join

                Studio Project Tag                  Position
0  Quality Engineering      ECOSYS  Quality Assurance Tester
1              Product      ECOSYS             Product Owner

In [41]:
data[data['Studio'] == 'Quality Engineering'][data['Position'] == 'Quality Assurance Tester'][data['Project Tag'] == 'ECOSYS']

/var/folders/0p/v_8rs5px14l8lggm7z70s1dw0000gn/T/ipykernel_99414/656581636.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Studio'] == 'Quality Engineering'][data['Position'] == 'Quality Assurance Tester'][data['Project Tag'] == 'ECOSYS']
/var/folders/0p/v_8rs5px14l8lggm7z70s1dw0000gn/T/ipykernel_99414/656581636.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Studio'] == 'Quality Engineering'][data['Position'] == 'Quality Assurance Tester'][data['Project Tag'] == 'ECOSYS']

,Date,Email,Name,Position,Seniority,Location,Studio,Client,Client Tag,Project,Project Tag,Team Name,Engagement,Email Leader,Year,Month,Day
1251,17Apr23,cristian.bravo@tec.globant.com,Cristian Bravo,Quality Assurance Tester,Sr Level 3,MX/JALISCO/GDL,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.78,NaN,2023,4,17
1252,18Apr23,cristian.bravo@tec.globant.com,Cristian Bravo,Quality Assurance Tester,Sr Level 3,MX/JALISCO/GDL,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.78,NaN,2023,4,18
1253,19Apr23,cristian.bravo@tec.globant.com,Cristian Bravo,Quality Assurance Tester,Sr Level 3,MX/JALISCO/GDL,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.78,NaN,2023,4,19
1254,20Apr23,cristian.bravo@tec.globant.com,Cristian Bravo,Quality Assurance Tester,Sr Level 3,MX/JALISCO/GDL,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.78,NaN,2023,4,20
1255,21Apr23,cristian.bravo@tec.globant.com,Cristian Bravo,Quality Assurance Tester,Sr Level 3,MX/JALISCO/GDL,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.78,NaN,2023,4,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1552,26Jun23,sergio.ceballos@tec.globant.com,Sergio Ceballos,Quality Assurance Tester,Ssr,MX/CDMX/CDMX,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.25,cristian.bravo@tec.globant.com,2023,6,26
1553,27Jun23,sergio.ceballos@tec.globant.com,Sergio Ceballos,Quality Assurance Tester,Ssr,MX/CDMX/CDMX,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.25,cristian.bravo@tec.globant.com,2023,6,27
1554,28Jun23,sergio.ceballos@tec.globant.com,Sergio Ceballos,Quality Assurance Tester,Ssr,MX/CDMX/CDMX,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.25,cristian.bravo@tec.globant.com,2023,6,28
1555,29Jun23,sergio.ceballos@tec.globant.com,Sergio Ceballos,Quality Assurance Tester,Ssr,MX/CDMX/CDMX,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,2.25,cristian.bravo@tec.globant.com,2023,6,29
1556,30Jun23,sergio.ceballos@tec.globant.com,Sergio Ceballos,Quality Assurance Tester,Ssr,MX/CDMX/CDMX,Quality Engineering,EcoBuild Enterprises,EBEPRI,Echo System,ECOSYS,Fight Club Penguin,0.24,cristian.bravo@tec.globant.com,2023,6,30